Add minor changes to be compatible with platform project
mdblp/tools pull request #28
Opened 2020-10-19 09:45 UTC by franck-fourel

2020-10-20 09:16 UTC, BigFab requested changes
Some request for changes inline.
I also need to test that on a "regular" Go project build to ensure the pipeline is not broken

2020-10-20 09:16 UTC, BigFab commented on artifact/artifact_go.sh
> +    fi
we should move these lines at the top so we can echo "Working on $APP" even if no argument is given

2020-10-20 09:16 UTC, BigFab commented on artifact/artifact_go.sh
> +    echo "Working on ${PARAM_APP_NAME}"
```suggestion
    echo "Working on ${APP}"
```

2020-10-20 11:51 UTC, franck-fourel commented on artifact/Readme.md
> +Artifact Tools
done

2020-10-20 11:52 UTC, franck-fourel commented on artifact/artifact_go.sh
> +    fi
done

2020-10-21 12:59 UTC, BigFab approved these changes
LGTM

2020-10-21 13:00 UTC, merged